version: '3.4'

services:
  assessment.api:
    image: ${DOCKER_REGISTRY-}assessmentapi
    container_name: assessment.api
    build:
      context: .
      dockerfile: BettingWorld.Assessment.Ishe.API/Dockerfile
    ports:
        - "5000:5000"
        - "5001:5001"
    depends_on: 
        - rates.mysql

  redis.cache:
    image: redis:latest
    restart: always
    container_name: redis.cache
    ports:
        - "6379:6379"

  rates.mysql:
    image: mysql:latest
    restart: always
    container_name: rates.mysql
    ports:
      - "3333:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'ExchangeRates'
      MYSQL_PASSWORD: 'password'
      MYSQL_User: 'dbuser'
    volumes:
      - ./.containers/mysql_data:/var/lib/mysql


